#ENC[AES256_GCM,data:88McA35XMcRDAj8ulMBcc5j1nh16eBK+bvMtUf4aGwP1WdZoc6Q1Bzvb4LiaZ7ZtrcXDVzILUS0=,iv:SAzjqYycbu6P2b6+L2r6T42NAhJpuN1k3wvtM/Vd3Mo=,tag:PixwvVE6RWY9TaRn8wBE9w==,type:comment]
#
#ENC[AES256_GCM,data:h9TWJmhOW4nw7jGGKEU63zowq24LolgWr8xBNC/GAgJL5NhOgI2n6lfKXf9jMOIoJvj4TyO+x1+6AshXJGFl9IQcxGNLfw==,iv:x7z0OR0K0z4zlKDqWr80CO14bIvMQZw/7uK/AKMMIBY=,tag:kfLLhxk/qP69eu4Wy1PGBg==,type:comment]
#ENC[AES256_GCM,data:kQ62WNk/c0ROkpqfRgws27WgerObrgdSaJ2Oyg+WdgH8i+/ANkwqeUJzkDiJwQnt+cfNRvvz81WEZ24QyUIal28pooUOXKnTZUWmrQ==,iv:I71sLbBgFuF5kirQEpdV5VCR/CnlJt33HGYLfH3riPk=,tag:5nEc8ixEvF6v54DJfR0hKA==,type:comment]
#ENC[AES256_GCM,data:zveli36yeoDZATzqtdbl+l8jiQ==,iv:O8kJd5P6cXMbukG6PU1vsDCyg+l0BZadrVmRpHo/ybg=,tag:Z+npEuIqLVTGP3OwOxvSLA==,type:comment]
#
#ENC[AES256_GCM,data:23iGa3wNXWJQFKnHJ2Adl6h0NYm2GEAhpIqFdrf/bZA8u8y6CebZbB885tzwXUZtkYslkaM0NsLd5WENluwmGeGS2Eo/+7p6kNw=,iv:0Ung8CRtg8887VUTWDrI2cNS6kVV6oYzmNyHbwNdNb8=,tag:KqzSyvAP+2Pvc8sbtm7CMA==,type:comment]
#ENC[AES256_GCM,data:20CyhwnwVZU4rwm6sYkc4Nv8SXDPXGy58PdHGjAW7+u5zswKUFkhe2+MucyYSfqWSQjNKCAYQTgedvMsB1oKjxsqq6sPYvhh,iv:vRw749CkCtq2Nk9RDIJNvSi8vjlbEiZE3XsNUYjmNHA=,tag:+n7p2Q3GMPvBWs69WOoBeQ==,type:comment]
#ENC[AES256_GCM,data:Nla2gHkGRCVgq5ZXai8kMTXXNP9s65JLHMdX3ZQA7rdnaMYZC7mVFVcT2VZnxfSBhuBuMDY=,iv:gwmDZr3znsf1hMCByh1eD32SCfY8orEdLD0DxDmgfp8=,tag:jqYOQNr8/GNT31ny6gx8Yg==,type:comment]
apiVersion: ENC[AES256_GCM,data:b1c=,iv:YvVn15Bkmb+C/9ZHJRdUcka5ctRdv0Ly29Q8VWVRhBg=,tag:YLq7l65YsmLeH8btPXH0nw==,type:str]
kind: ENC[AES256_GCM,data:0SDe2Ycg,iv:nxkqer4OXVLAmmVVcCYugeGMAQvQUMQRBU/HcgtEef4=,tag:b7o9fdemMiYCJFnncdXAkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E/Tow44YMNAmfL4gJkQ=,iv:ur5fPqgLs3QEb1e3RbhNjg0u7UbJz09jcA7/Kwf+YVk=,tag:CyjnRbh0XR+VSuZtbB9MeQ==,type:str]
    namespace: ENC[AES256_GCM,data:hnFFHcje2uUx,iv:m5NWF9Ufew/w8opXo581tNeCS4sNQJ+7yUWScm3Mgis=,tag:8UVc/ZI3ixuDDp41Vl08kw==,type:str]
type: ENC[AES256_GCM,data:LUACYyIN,iv:iq/12HmXM1JuPVgmf1kwMFUK523Td73UZBXQbQ/H9Qg=,tag:3TiDSKx+55OH6hLGotOqEg==,type:str]
data:
    client_id: ENC[AES256_GCM,data:iPuTl2NrvLxEsTYfvHBmjQe7VR2izk+m,iv:DHe2EylSe9CbG/gvMlpqCGBbbNqdvz5rfY8KMoj57V8=,tag:Qw1Y9hsWPqyX1MnpxXEbqw==,type:str]
    client_secret: ENC[AES256_GCM,data:tabO4WLBmTAa0VqquK8NSREVUy3INf//Y6DLRScopH7cLIs6k0aFOuJxadR5vJpYTBFL70wryOyxhZMe//iWqgVn8hZOfNCXmRCZS4Jk6L+dKz4o,iv:bPOrkBF2I+k6NpsQ359KxeSyY8VwBXLOKBWBrNoXWCA=,tag:k098maprSMHF67dB2otqag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y0NaVFFkRkNiZVRZSHYw
            dW5VU2RYWlpxT0R6SWVQV1BVNXR1blAwWlM4CjZWUW9hYy9UOG1Yd2RmMGRYRUt3
            YWswbEE3cnpCWW91L1lkUXpDRTI0ZmcKLS0tIFBiYWlYSExUZnR2YUJDRE9nSm5a
            VUpxUUNFU01ydDdMRWVXSWo4VURYRWcKEyd2UNFGBJYa7VRf2hH68UvHifwDiIe5
            Rc/qRqYJXoH00NpNVqb0lCbCZbyB6fgbP0WYgSp1YmpAKjs5xPQsig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13zf2gl0kqnajw9g22qxfx6h80qkgl00m8t8akk6cqfj9s2xwx4ps8jlvzn
    lastmodified: "2026-06-27T15:48:28Z"
    mac: ENC[AES256_GCM,data:AwuktySQB/AucdtHFboNDzq9rlvTC4szlc0X/elRzF/THZcgmo8+LXdgB/FBJkBNJsA6w7PPMCiTpsDgKNaclzOCk4INsATorlkfmyvzyzcfIBEcQT98N9CAju1lBpRXJi4FcoTxxxpCeaoOv4uo+3RO8JPHR9jHzuVFQN8PzMY=,iv:1VyA8BM4pCkGjrg1EB2Jlsqb7e0C8XwEMS2hHv7ok+o=,tag:vGAwdfTet2YYdDJjbpx5RQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
