apiVersion: ENC[AES256_GCM,data:1hM=,iv:NLN3DDhpc12/g1CS74cx7VmzfZlh6QXbEIjvVgZiZ+k=,tag:mCDw8WuF2NXNSt4f5SgwEQ==,type:str]
kind: ENC[AES256_GCM,data:p3ouulhN,iv:/LHdQnM0EQuctus/j9GJXYGmTnrVAuFHfdyR+YWfsbQ=,tag:nA6ZXg8XrM8okioPiihfiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BVRO6NXLAMu79xw6l/Q/Y7ldRkooyYM=,iv:wqT559Uc19/SuShJkeCuBJ5gBwxpmJ6ntjok451sf88=,tag:fXX8mo7DIdhszIMb5tAOBw==,type:str]
    namespace: ENC[AES256_GCM,data:f8MatvzVjGM1,iv:s5gsFBRPoTrO7uubjeYw++7iXjA10y7z21h8pa+vDW4=,tag:e4WTvPQjvUvqXAAr/aCjGw==,type:str]
type: ENC[AES256_GCM,data:g2jSR9og,iv:9Wc8UBmhBMJAjtj35LXVIRSEJlG09ICbWu1DTlIYRPc=,tag:CVfbQtISKYxNSMY4dbK/wA==,type:str]
data:
    TS_AUTH_KEY: ENC[AES256_GCM,data:PFrrMoWKGGM4ozxTf0PpdXGLBOJaYNFSBxzUb1x5Zez0KYIgXGduhlkxfXoVmhjrU/ouib+ssuGLbBsRR2I/dexU7n6maOSHhnr4nHAIjU/ehxlF,iv:rVrOp9rTeJHr0Qeyltgsh9Lc0vXHHYuNFgKihKAOlts=,tag:7aaqXvEXbsXMqmGFQDNN8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMjZzL2Y1Q1c1WmRkMnNa
            VTJYU01IdkZTa0ExV2ZPRTI1V0hwZlh5a3hNCmdEdU1WVUhweXVuQ0w5M1pCRlA2
            eGNxUGJRRCs1bG96dkE1VitOdTFrQUkKLS0tIFFiQ2dQL3dFSzQzQnBySXRxK3Zo
            NVBnRzl1SGdnMHpFcEwvQXdNcWgweFEK6lG6t0zS4SUSb8gP/Ft1pOTDcqoWDsmV
            NzBR+fRvfAcY5mWypJVUO8NL3/ELCC7Fv2QDxyPe1NzVc/s42AXpZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13zf2gl0kqnajw9g22qxfx6h80qkgl00m8t8akk6cqfj9s2xwx4ps8jlvzn
    lastmodified: "2026-06-27T15:07:10Z"
    mac: ENC[AES256_GCM,data:PrcsfEFCg68hjHrUdDtMBZh3lKpl8tB26Pd8t+adSWZAVAV9O+G0HUXVrobjDP+QvoQXpgwDJTw7jRWQhtW0QkDu8c/RdWQR/lKMWT9XXdl6Yir1Mbq/DzZhRaHRLrbPr11FGXDMp7Ibp9TdFAYuYpCJ040TgIBRUs3zW765uPk=,iv:7GprHtL9BBbYVNSQm3WeBd4aylWfWo/jy/EJNvb9V+E=,tag:zPwNRVNZlKaCtcJR4MdYog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
