apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homelab:minecraft-operators
  namespace: minecraft
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: homelab:minecraft-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homelab:namespace-operator
