apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment/configmap.yaml
- deployment/deployment.yaml
- deployment/dns-updater.yaml
- deployment/namespace.yaml
- deployment/pvc.yaml
- deployment/service.yaml
- deployment/tunnel.yaml

secretGenerator:
- name: minecraft-dns-secret
  namespace: minecraft
  env: config/env.secret

configMapGenerator:
- name: mod-config
  namespace: minecraft
  files:
  - config/mod-list.txt
