---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aitrade
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: aitrade-auth
  url: https://github.com/Englios/ai-trade.git
