apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bore-tunnel
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate  # This ensures old pod terminates before new one starts
  selector:
    matchLabels:
      app: minecraft-bore-tunnel
  template:
    metadata:
      labels:
        app: minecraft-bore-tunnel
    spec:
      terminationGracePeriodSeconds: 60  # Give pod 60 seconds to shut down gracefully
      containers:
      - name: bore-tunnel
        image: ekzhang/bore:latest
        # Use the default entrypoint ["./bore"] from the image
        args:
          - "local"
          - "25565"
          - "--to"
          - "$(BORE_SERVER_IP)"
          - "--local-host"
          - "minecraft-server.minecraft.svc.cluster.local"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        env:
        - name: RUST_LOG
          value: "info"
        - name: BORE_SERVER_IP
          valueFrom:
            secretKeyRef:
              name: bore-server-config
              key: server-ip
        - name: BORE_SERVER_TYPE
          valueFrom:
            secretKeyRef:
              name: bore-server-config
              key: server-type
      - name: health-monitor
        image: busybox:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # Simple HTTP health server that checks if bore tunnel is working
            echo "ðŸ” Starting bore tunnel health monitor..."
            
            # Create a simple health check server
            while true; do
              # Test if we can connect to minecraft server (bore tunnel target)
              if nc -z minecraft-server.minecraft.svc.cluster.local 25565 2>/dev/null; then
                echo "HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK" | nc -l -p 8080 -q 1 || true
              else
                echo "HTTP/1.1 503 Service Unavailable\r\nContent-Length: 5\r\n\r\nERROR" | nc -l -p 8080 -q 1 || true
              fi
            done
        ports:
        - containerPort: 8080
          name: health
        resources:
          requests:
            memory: "8Mi"
            cpu: "5m"
          limits:
            memory: "16Mi"
            cpu: "20m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
      restartPolicy: Always 