apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bore-tunnel
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate  # This ensures old pod terminates before new one starts
  selector:
    matchLabels:
      app: minecraft-bore-tunnel
  template:
    metadata:
      labels:
        app: minecraft-bore-tunnel
    spec:
      terminationGracePeriodSeconds: 60  # Give pod 60 seconds to shut down gracefully
      containers:
      - name: bore-tunnel
        image: ekzhang/bore:latest
        # Use the default entrypoint ["./bore"] from the image
        args:
          - "local"
          - "25565"
          - "--to"
          - "$(BORE_SERVER_IP)"
          - "--local-host"
          - "minecraft-server.minecraft.svc.cluster.local"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        env:
        - name: RUST_LOG
          value: "info"
        - name: BORE_SERVER_IP
          valueFrom:
            secretKeyRef:
              name: bore-server-config
              key: server-ip
        - name: BORE_SERVER_TYPE
          valueFrom:
            secretKeyRef:
              name: bore-server-config
              key: server-type
        # Note: Health probes removed as the bore image doesn't expose the tunneled port locally
        # Kubernetes will restart the pod if it crashes
      restartPolicy: Always 