apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-dns-config
  namespace: minecraft
data:
  MINECRAFT_DOMAIN: "play-mc.alifaiman.cloud"
  MINECRAFT_SUBDOMAIN: "play-mc"
  BASE_DOMAIN: "alifaiman.cloud"
  A_RECORD_NAME: "play-mc"
  SRV_RECORD_NAME: "_minecraft._tcp.play-mc"
  CUSTOM_SRV_NAME: "_minecraft.play-mc"
  DNS_TTL: "300"
  SRV_PRIORITY: "0"
  SRV_WEIGHT: "5"
  # Simple port pool for manual rotation
  MINECRAFT_TCP_PORT: "35000"  # Can easily change these
  MINECRAFT_UDP_PORT: "35001"
  # Alternative ports: 35010/35011, 35020/35021, 35030/35031
