apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
          name: minecraft
        env:
        - name: SERVER_NAME
          value: "MAAF Server"
        - name: EULA
          value: "TRUE"
        - name: MODPACK_PLATFORM
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "better-mc-forge-bmc4"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-api
              key: api-key
        - name: MEMORY
          value: "6G"
        - name: FORCE_REINSTALL
          value: "true"
        - name: MAX_PLAYERS
          value: "20"
        - name: DIFFICULTY
          value: "normal"
        - name: ALLOW_NETHER
          value: "true"
        - name: ALLOW_END
          value: "true"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "true"
        - name: GENERATE_STRUCTURES
          value: "true"
        - name: HARDCORE
          value: "false"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: MAX_WORLD_SIZE
          value: "29999984"  # Large world
        - name: PVP
          value: "true"
        - name: SPAWN_ANIMALS
          value: "true"
        - name: SPAWN_MONSTERS
          value: "true"
        - name: SPAWN_NPCS
          value: "true"
        - name: VIEW_DISTANCE
          value: "7"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: PLAYER_IDLE_TIMEOUT
          value: "0"
        - name: JVM_OPTS
          value: "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=15 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90"
        - name: SIMULATION_DISTANCE
          value: "6"
        - name: ENTITY_BROADCAST_RANGE_PERCENTAGE
          value: "80"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
          initialDelaySeconds: 120
          periodSeconds: 60
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
              