apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  revisionHistoryLimit: 3  # Keep only 3 old ReplicaSets for rollback
  strategy:
    type: Recreate  # Terminate old pod before creating new one (avoids memory issues)
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        - containerPort: 24454
          name: voice-chat
          protocol: UDP
        env:
        - name: SERVER_NAME
          value: "MAAF Server"
        - name: EULA
          value: "TRUE"
        - name: MODPACK_PLATFORM
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "better-mc-forge-bmc4"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-api
              key: api-key
        - name: MEMORY
          value: "6G"  # Reduced from 8G - better GC performance
        - name: FORCE_REINSTALL
          value: "true"
        - name: REMOVE_OLD_FORGE_INSTALLER
          value: "true"
        - name: MAX_PLAYERS
          value: "20"
        - name: DIFFICULTY
          value: "normal"
        - name: ALLOW_NETHER
          value: "true"
        - name: ALLOW_END
          value: "true"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "true"
        - name: GENERATE_STRUCTURES
          value: "true"
        - name: HARDCORE
          value: "false"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: MAX_WORLD_SIZE
          value: "29999984"  # Large world
        - name: PVP
          value: "true"
        - name: SPAWN_ANIMALS
          value: "true"
        - name: SPAWN_MONSTERS
          value: "true"
        - name: SPAWN_NPCS
          value: "true"
        - name: VIEW_DISTANCE
          value: "5"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: PLAYER_IDLE_TIMEOUT
          value: "0"
        - name: JVM_OPTS
          value: "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
        - name: SIMULATION_DISTANCE
          value: "4"
        - name: ENTITY_BROADCAST_RANGE_PERCENTAGE
          value: "60"
        # Performance optimizations for combat
        - name: MAX_TICK_TIME
          value: "60000"
        - name: NETWORK_COMPRESSION_THRESHOLD
          value: "256"
        - name: SPAWN_PROTECTION
          value: "0"
        # Better performance settings that don't break gameplay
        - name: ENTITY_ACTIVATION_RANGE_ANIMALS
          value: "16"
        - name: ENTITY_ACTIVATION_RANGE_MONSTERS  
          value: "24"
        - name: ENTITY_ACTIVATION_RANGE_MISC
          value: "8"
        - name: MOB_SPAWN_RANGE
          value: "6"
        - name: CURSEFORGE_FILES
          value: "416089"
        - name: REMOVE_OLD_MODS
          value: "true"
        - name: MOTD
          value: "§6§l ALif MC Server §r§8| §a§lNEW: Voice Chat! §r§8| §7Press V in-game"
        resources:
          requests:
            memory: "7Gi"  # 6GB Java heap + 1GB overhead
            cpu: "300m"    # Conservative for small player count
          limits:
            memory: "9Gi"  # 6GB Java heap + 3GB max overhead
            cpu: "1500m"   # Enough for peak times
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        - name: voicechat-config
          mountPath: /data/config/voicechat/voicechat-server.properties
          subPath: voicechat-server.properties
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
          initialDelaySeconds: 90   # Start checking after 1.5 minutes
          periodSeconds: 10         # Check every 10 seconds
          failureThreshold: 30      # Allow 30 failures = 5 more minutes
          successThreshold: 2       # Need 2 consecutive successes (more stable)
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
          initialDelaySeconds: 300  # Wait 5 minutes before first check
          periodSeconds: 60         # Check every 1 minute
          failureThreshold: 5       # Allow 5 failures = 5 more minutes
          timeoutSeconds: 10        # Give command 10 seconds to respond
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
      - name: voicechat-config
        configMap:
          name: voicechat-config
  revisionHistoryLimit: 3  # Keep only 3 old ReplicaSets
              