apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
          name: minecraft
          protocol: TCP
        - containerPort: 24454
          name: voice-chat
          protocol: UDP
        env:
        - name: SERVER_NAME
          value: "MAAF Server"
        - name: EULA
          value: "TRUE"
        - name: MODPACK_PLATFORM
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "better-mc-forge-bmc4"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-api
              key: api-key
        - name: MEMORY
          value: "7G"
        - name: FORCE_REINSTALL
          value: "true"
        - name: REMOVE_OLD_FORGE_INSTALLER
          value: "true"
        - name: MAX_PLAYERS
          value: "20"
        - name: DIFFICULTY
          value: "normal"
        - name: ALLOW_NETHER
          value: "true"
        - name: ALLOW_END
          value: "true"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "true"
        - name: GENERATE_STRUCTURES
          value: "true"
        - name: HARDCORE
          value: "false"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: MAX_WORLD_SIZE
          value: "29999984"  # Large world
        - name: PVP
          value: "true"
        - name: SPAWN_ANIMALS
          value: "true"
        - name: SPAWN_MONSTERS
          value: "true"
        - name: SPAWN_NPCS
          value: "true"
        - name: VIEW_DISTANCE
          value: "5"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: PLAYER_IDLE_TIMEOUT
          value: "0"
        - name: JVM_OPTS
          value: "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
        - name: SIMULATION_DISTANCE
          value: "4"
        - name: ENTITY_BROADCAST_RANGE_PERCENTAGE
          value: "60"
        # Performance optimizations for combat
        - name: MAX_TICK_TIME
          value: "60000"
        - name: NETWORK_COMPRESSION_THRESHOLD
          value: "256"
        - name: SPAWN_PROTECTION
          value: "0"
        # Better performance settings that don't break gameplay
        - name: ENTITY_ACTIVATION_RANGE_ANIMALS
          value: "16"
        - name: ENTITY_ACTIVATION_RANGE_MONSTERS  
          value: "24"
        - name: ENTITY_ACTIVATION_RANGE_MISC
          value: "8"
        - name: MOB_SPAWN_RANGE
          value: "6"
        - name: CURSEFORGE_FILES
          value: "416089"
        - name: REMOVE_OLD_MODS
          value: "true"
        - name: MOTD
          value: "§6§l ALif MC Server §r§8| §a§lNEW: Voice Chat! §r§8| §7Press V in-game"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        - name: voicechat-config
          mountPath: /data/config/voicechat/voicechat-server.properties
          subPath: voicechat-server.properties
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
          initialDelaySeconds: 420  # Wait 7 minutes before first check
          periodSeconds: 30         # Check every 30 seconds
          failureThreshold: 40      # Allow 40 failures = 20 more minutes
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
          initialDelaySeconds: 900  # Wait 15 minutes before first check
          periodSeconds: 120        # Check every 2 minutes  
          failureThreshold: 10      # Allow 10 failures = 20 more minutes
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
      - name: voicechat-config
        configMap:
          name: voicechat-config
              