apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: minecraft