apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-tunnel
  namespace: minecraft
spec:
  revisionHistoryLimit: 3  # Keep only 3 old ReplicaSets for rollback
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-tunnel
  template:
    metadata:
      labels:
        app: minecraft-tunnel
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: rtun-client
        image: snsinfu/rtun
        env:
        - name: RTUN_GATEWAY
          valueFrom:
            secretKeyRef:
              name: rtun-config
              key: gateway-url
        - name: RTUN_KEY
          valueFrom:
            secretKeyRef:
              name: tunnel-server-config
              key: auth
        - name: RTUN_FORWARD
          value: "35000/tcp:minecraft-server.minecraft.svc.cluster.local:25565,35001/udp:minecraft-server.minecraft.svc.cluster.local:24454"
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "pgrep rtun > /dev/null"
          initialDelaySeconds: 30
          periodSeconds: 60

      # Health monitoring container
      - name: debug-logger
        image: busybox:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "📊 Debug Logger Started - Monitoring rtun tunnel"
            echo "Logging tunnel info every 60 seconds..."
            
            while true; do
              echo "🔍 $(date): Tunnel Status Check"
              
              # Log rtun process status
              rtun_running=false
              tcp_reachable=false
              udp_reachable=false
              
              if pgrep -f "rtun" > /dev/null; then
                echo "✅ rtun client process: Running"
                rtun_running=true
              else
                echo "❌ rtun client process: Not found"
              fi
              
              # Test TCP connectivity to Minecraft server
              if nc -z minecraft-server.minecraft.svc.cluster.local 25565 2>/dev/null; then
                echo "✅ Internal Minecraft server (TCP 25565): Reachable"
                tcp_reachable=true
              else
                echo "❌ Internal Minecraft server (TCP 25565): Unreachable"
              fi
              
              # Test UDP connectivity to Voice Chat server
              if timeout 3 nc -u minecraft-server.minecraft.svc.cluster.local 24454 < /dev/null 2>/dev/null; then
                echo "✅ Internal voice chat server (UDP 24454): Reachable"
                udp_reachable=true
              else
                # Try a different UDP test method
                if echo "test" | timeout 2 nc -u -w1 minecraft-server.minecraft.svc.cluster.local 24454 2>/dev/null; then
                  echo "✅ Internal voice chat server (UDP 24454): Reachable"
                  udp_reachable=true
                else
                  echo "⚠️  Internal voice chat server (UDP 24454): Test inconclusive"
                fi
              fi
              
              # Overall health status - require rtun running and TCP connectivity
              # UDP is nice-to-have but not required for health
              if $rtun_running && $tcp_reachable; then
                echo "🟢 Overall tunnel health: HEALTHY"
                echo "healthy" > /tmp/health
              else
                echo "🔴 Overall tunnel health: UNHEALTHY"
                rm -f /tmp/health 2>/dev/null || true
              fi
              
              echo ""
              sleep 60
            done
        resources:
          requests:
            memory: "8Mi"
            cpu: "5m" 
          limits:
            memory: "16Mi"
            cpu: "20m"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -f /tmp/health"
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -f /tmp/health"
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3

      restartPolicy: Always