apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-tunnel
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-tunnel
  template:
    metadata:
      labels:
        app: minecraft-tunnel
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: tunnel
        image: jpillora/chisel:latest
        args:
          - "client"
          - "-v"
          - "--auth"
          - "$(TUNNEL_AUTH)"
          - "http://$(TUNNEL_SERVER_IP):8080"
          # Simple configurable ports
          - "R:$(MINECRAFT_TCP_PORT):minecraft-server.minecraft.svc.cluster.local:25565"
          - "R:$(MINECRAFT_UDP_PORT):minecraft-server.minecraft.svc.cluster.local:24454"
        env:
        - name: TUNNEL_SERVER_IP
          valueFrom:
            secretKeyRef:
              name: tunnel-server-config
              key: server-ip
        - name: TUNNEL_AUTH
          valueFrom:
            secretKeyRef:
              name: tunnel-server-config
              key: auth
        - name: MINECRAFT_TCP_PORT
          valueFrom:
            configMapKeyRef:
              name: minecraft-dns-config
              key: MINECRAFT_TCP_PORT
        - name: MINECRAFT_UDP_PORT
          valueFrom:
            configMapKeyRef:
              name: minecraft-dns-config
              key: MINECRAFT_UDP_PORT
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        # Remove health probes - chisel image is too minimal
      # Keep debug-logger (busybox has shell)
      - name: debug-logger
        image: busybox:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "📊 Debug Logger Started"
            echo "Logging tunnel info every 60 seconds..."
            
            while true; do
              echo "🔍 $(date): Tunnel Status Check"
              
              # Log chisel process status
              if pgrep -f "chisel client" > /dev/null; then
                echo "✅ Chisel process: Running"
                echo "healthy" > /tmp/health  # Create health file
              else
                echo "❌ Chisel process: Not found"
                rm -f /tmp/health 2>/dev/null || true  # Remove health file
              fi
              
              # Log network connections (to see active ports)
              echo "📡 Active connections:"
              netstat -tln 2>/dev/null | grep LISTEN | grep -v ':22' | head -5 || echo "   No listening ports found"
              
              # Log internal server connectivity
              if nc -z minecraft-server.minecraft.svc.cluster.local 25565 2>/dev/null; then
                echo "✅ Internal Minecraft server: Reachable"
              else
                echo "❌ Internal Minecraft server: Unreachable"
              fi
              
              echo ""
              sleep 60
            done
        resources:
          requests:
            memory: "8Mi"
            cpu: "5m" 
          limits:
            memory: "16Mi"
            cpu: "20m"
        # Add health checks to debug-logger (monitors chisel too)
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -f /tmp/health"
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -f /tmp/health"
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
      restartPolicy: Always