tls-san:
  - <TAILSCALE_IP>
kube-apiserver-arg:
  - oidc-issuer-url=https://<OIDC_TAILSCALE_HOSTNAME>/application/o/kubernetes/
  - oidc-client-id=kubernetes
  - oidc-username-claim=email
  - oidc-groups-claim=groups
  - oidc-username-prefix=oidc:
  - oidc-groups-prefix=oidc:
  - oidc-ca-file=/etc/rancher/k3s/oidc/ca.crt
