---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ts-charts
  namespace: flux-system
spec:
  type: default
  url: https://pkgs.tailscale.com/helmcharts
  interval: 24h
