apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bore-server
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bore-server
  template:
    metadata:
      labels:
        app: bore-server
    spec:
      containers:
      - name: bore-server
        image: alpine:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            apk add --no-cache curl
            curl -L https://github.com/ekzhang/bore/releases/download/v0.6.0/bore-v0.6.0-x86_64-unknown-linux-musl.tar.gz | tar xz
            chmod +x bore
            echo "🏠 Starting homelab bore server..."
            echo "Server will listen on port 7835"
            echo "Clients can connect to: YOUR_PUBLIC_IP:7835"
            ./bore server --min-port 1024 --max-port 65535
        ports:
        - containerPort: 7835
          name: bore-server
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 7835
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 7835
          initialDelaySeconds: 10
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: bore-server
  namespace: infrastructure
spec:
  type: LoadBalancer
  ports:
  - port: 7835
    targetPort: 7835
    name: bore-server
    protocol: TCP
  selector:
    app: bore-server

---
# Service for tunnel ports - using NodePort for port range access
apiVersion: v1
kind: Service
metadata:
  name: bore-tunnels
  namespace: infrastructure
spec:
  type: NodePort
  ports:
  - port: 12385
    targetPort: 12385
    nodePort: 32385
    name: tunnel-12385
    protocol: TCP
  selector:
    app: bore-server 