apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homelab:automation-bot:oidc-cluster-readonly
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:service-account-homelab-automation-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homelab:automation-bot:cluster-readonly
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homelab:automation-bot:oidc-namespaced-readonly
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:service-account-homelab-automation-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homelab:automation-bot:namespaced-readonly
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homelab-automation-bot-oidc
  namespace: inference-engine
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:service-account-homelab-automation-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homelab-automation-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homelab-automation-bot-oidc
  namespace: experiment
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:service-account-homelab-automation-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homelab-automation-bot
