apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: homelab-automation-bot
  namespace: experiment
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward", "services/proxy"]
  verbs: ["create"]
